
#[derive(Debug, Copy, Clone, serde::Deserialize, serde::Serialize, Ord, PartialOrd, Eq, PartialEq, Hash)]
pub enum ModelId {
Ada,
AdaCodeSearchCode,
AdaCodeSearchText,
AdaSearchDocument,
AdaSearchQuery,
AdaSimilarity,
AdaColon20200503,
AudioTranscribeDeprecated,
Babbage,
BabbageCodeSearchCode,
BabbageCodeSearchText,
BabbageSearchDocument,
BabbageSearchQuery,
BabbageSimilarity,
BabbageColon20200503,
CodeCushman001,
CodeDavinci002,
CodeDavinciEdit001,
CodeSearchAdaCode001,
CodeSearchAdaText001,
CodeSearchBabbageCode001,
CodeSearchBabbageText001,
Curie,
CurieInstructBeta,
CurieSearchDocument,
CurieSearchQuery,
CurieSimilarity,
CurieColon20200503,
CushmanColon20200503,
Davinci,
DavinciIfColon3Period0Period0,
DavinciInstructBeta,
DavinciInstructBetaColon2Period0Period0,
DavinciSearchDocument,
DavinciSearchQuery,
DavinciSimilarity,
DavinciColon20200503,
Gpt3Period5Turbo,
Gpt3Period5Turbo0301,
IfCurieV2,
IfDavinciV2,
IfDavinciColon3Period0Period0,
TextAda001,
TextAdaColon001,
TextBabbage001,
TextBabbageColon001,
TextCurie001,
TextCurieColon001,
TextDavinci001,
TextDavinci002,
TextDavinci003,
TextDavinciEdit001,
TextDavinciInsert001,
TextDavinciInsert002,
TextDavinciColon001,
TextEmbeddingAda002,
TextSearchAdaDoc001,
TextSearchAdaQuery001,
TextSearchBabbageDoc001,
TextSearchBabbageQuery001,
TextSearchCurieDoc001,
TextSearchCurieQuery001,
TextSearchDavinciDoc001,
TextSearchDavinciQuery001,
TextSimilarityAda001,
TextSimilarityBabbage001,
TextSimilarityCurie001,
TextSimilarityDavinci001,
Whisper1,

}

impl core::fmt::Display for ModelId {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
ModelId::Ada => "ada",
ModelId::AdaCodeSearchCode => "ada-code-search-code",
ModelId::AdaCodeSearchText => "ada-code-search-text",
ModelId::AdaSearchDocument => "ada-search-document",
ModelId::AdaSearchQuery => "ada-search-query",
ModelId::AdaSimilarity => "ada-similarity",
ModelId::AdaColon20200503 => "ada:2020-05-03",
ModelId::AudioTranscribeDeprecated => "audio-transcribe-deprecated",
ModelId::Babbage => "babbage",
ModelId::BabbageCodeSearchCode => "babbage-code-search-code",
ModelId::BabbageCodeSearchText => "babbage-code-search-text",
ModelId::BabbageSearchDocument => "babbage-search-document",
ModelId::BabbageSearchQuery => "babbage-search-query",
ModelId::BabbageSimilarity => "babbage-similarity",
ModelId::BabbageColon20200503 => "babbage:2020-05-03",
ModelId::CodeCushman001 => "code-cushman-001",
ModelId::CodeDavinci002 => "code-davinci-002",
ModelId::CodeDavinciEdit001 => "code-davinci-edit-001",
ModelId::CodeSearchAdaCode001 => "code-search-ada-code-001",
ModelId::CodeSearchAdaText001 => "code-search-ada-text-001",
ModelId::CodeSearchBabbageCode001 => "code-search-babbage-code-001",
ModelId::CodeSearchBabbageText001 => "code-search-babbage-text-001",
ModelId::Curie => "curie",
ModelId::CurieInstructBeta => "curie-instruct-beta",
ModelId::CurieSearchDocument => "curie-search-document",
ModelId::CurieSearchQuery => "curie-search-query",
ModelId::CurieSimilarity => "curie-similarity",
ModelId::CurieColon20200503 => "curie:2020-05-03",
ModelId::CushmanColon20200503 => "cushman:2020-05-03",
ModelId::Davinci => "davinci",
ModelId::DavinciIfColon3Period0Period0 => "davinci-if:3.0.0",
ModelId::DavinciInstructBeta => "davinci-instruct-beta",
ModelId::DavinciInstructBetaColon2Period0Period0 => "davinci-instruct-beta:2.0.0",
ModelId::DavinciSearchDocument => "davinci-search-document",
ModelId::DavinciSearchQuery => "davinci-search-query",
ModelId::DavinciSimilarity => "davinci-similarity",
ModelId::DavinciColon20200503 => "davinci:2020-05-03",
ModelId::Gpt3Period5Turbo => "gpt-3.5-turbo",
ModelId::Gpt3Period5Turbo0301 => "gpt-3.5-turbo-0301",
ModelId::IfCurieV2 => "if-curie-v2",
ModelId::IfDavinciV2 => "if-davinci-v2",
ModelId::IfDavinciColon3Period0Period0 => "if-davinci:3.0.0",
ModelId::TextAda001 => "text-ada-001",
ModelId::TextAdaColon001 => "text-ada:001",
ModelId::TextBabbage001 => "text-babbage-001",
ModelId::TextBabbageColon001 => "text-babbage:001",
ModelId::TextCurie001 => "text-curie-001",
ModelId::TextCurieColon001 => "text-curie:001",
ModelId::TextDavinci001 => "text-davinci-001",
ModelId::TextDavinci002 => "text-davinci-002",
ModelId::TextDavinci003 => "text-davinci-003",
ModelId::TextDavinciEdit001 => "text-davinci-edit-001",
ModelId::TextDavinciInsert001 => "text-davinci-insert-001",
ModelId::TextDavinciInsert002 => "text-davinci-insert-002",
ModelId::TextDavinciColon001 => "text-davinci:001",
ModelId::TextEmbeddingAda002 => "text-embedding-ada-002",
ModelId::TextSearchAdaDoc001 => "text-search-ada-doc-001",
ModelId::TextSearchAdaQuery001 => "text-search-ada-query-001",
ModelId::TextSearchBabbageDoc001 => "text-search-babbage-doc-001",
ModelId::TextSearchBabbageQuery001 => "text-search-babbage-query-001",
ModelId::TextSearchCurieDoc001 => "text-search-curie-doc-001",
ModelId::TextSearchCurieQuery001 => "text-search-curie-query-001",
ModelId::TextSearchDavinciDoc001 => "text-search-davinci-doc-001",
ModelId::TextSearchDavinciQuery001 => "text-search-davinci-query-001",
ModelId::TextSimilarityAda001 => "text-similarity-ada-001",
ModelId::TextSimilarityBabbage001 => "text-similarity-babbage-001",
ModelId::TextSimilarityCurie001 => "text-similarity-curie-001",
ModelId::TextSimilarityDavinci001 => "text-similarity-davinci-001",
ModelId::Whisper1 => "whisper-1",

        };
        write!(f, "{}", s)
    }
}